var names = "数据挖掘233";

//学科
var subject=[
    {   "subjectId":"000",
        "subjectName":"",
        "address":"多媒体(北)"
    },
    {   "subjectId":"001",
        "subjectName":"程序设计基础",
        "address":"多媒体(北)"
    },
    {
        "subjectId":"002",
        "subjectName":"程序设计上机",
        "address":"多媒体(北)"
    },
    {
        "subjectId":"003",
        "subjectName":"物联网",
        "address":"多媒体(北)"
    }
];

//var classTime{
//    [0118,], [],[],[]
//}

var time = {
    "teacherId":"001",
    "teacherName":"鲁力",
    "semesterId":"1",
    "semester":"2015第一学期",
    "teacherSex":"男",
    "week":[
        {
            //周日
            "day":"sunday",
            "course":[
                //第一节课
                {
                    "startTime":"8:30",
                    "endTime":"10:05",
                    "subject":subject[0].subjectName
                },
                //第二节课
                {
                    "startTime":"10:25",
                    "endTime":"12:00",
                    "subject":subject[0].subjectName
                },
                //第三节课
                {
                    "startTime":"01:50",
                    "endTime":"03:05",
                    "subject":subject[0].subjectName
                },
                //第四节课
                {
                    "startTime":"3:25",
                    "endTime":"5:00",
                    "subject":subject[0].subjectName
                },
                //第五节课
                {
                    "startTime":"6:30",
                    "endTime":"8:05",
                    "subject":subject[0].subjectName
                },
                //第六节课
                {
                    "startTime":"8:25",
                    "endTime":"10:00",
                    "subject":subject[0].subjectName
                }
            ]
        },
        {
            //周一
            "day":"monday",
            "course":[
                //第一节课
                {
                    "startTime":"8:30",
                    "endTime":"10:05",
                    "subject":subject[0].subjectName
                },
                //第二节课
                {
                    "startTime":"10:25",
                    "endTime":"12:00",
                    "subject":subject[0].subjectName
                },
                //第三节课
                {
                    "startTime":"01:50",
                    "endTime":"03:05",
                    "subject":subject[0].subjectName
                },
                //第四节课
                {
                    "startTime":"3:25",
                    "endTime":"5:00",
                    "subject":subject[0].subjectName
                },
                //第五节课
                {
                    "startTime":"6:30",
                    "endTime":"8:05",
                    "subject":subject[0].subjectName
                },
                //第六节课
                {
                    "startTime":"8:25",
                    "endTime":"10:00",
                    "subject":subject[0].subjectName
                }
            ]
        },
        {   //周二
            "day":"tuesday",
            "course":[
                //第一节课
                {
                    "startTime":"8:30",
                    "endTime":"10:05",
                    "subject":subject[1].subjectName
                },
                //第二节课
                {
                    "startTime":"10:25",
                    "endTime":"12:00",
                    "subject":subject[0].subjectName
                },
                //第三节课
                {
                    "startTime":"01:50",
                    "endTime":"03:05",
                    "subject":subject[2].subjectName
                },
                //第四节课
                {
                    "startTime":"3:25",
                    "endTime":"5:00",
                    "subject":subject[2].subjectName
                },
                //第五节课
                {
                    "startTime":"6:30",
                    "endTime":"8:05",
                    "subject":subject[0].subjectName
                },
                //第六节课
                {
                    "startTime":"8:25",
                    "endTime":"10:00",
                    "subject":subject[0].subjectName
                }
            ]
        },
        {
            //周三
            "day":"wednesday",
            "course":[
                //第一节课
                {
                    "startTime":"8:30",
                    "endTime":"10:05",
                    "subject":subject[0].subjectName
                },
                //第二节课
                {
                    "startTime":"10:25",
                    "endTime":"12:00",
                    "subject":subject[0].subjectName
                },
                //第三节课
                {
                    "startTime":"01:50",
                    "endTime":"03:05",
                    "subject":subject[0].subjectName
                },
                //第四节课
                {
                    "startTime":"3:25",
                    "endTime":"5:00",
                    "subject":subject[0].subjectName
                },
                //第五节课
                {
                    "startTime":"6:30",
                    "endTime":"8:05",
                    "subject":subject[0].subjectName
                },
                //第六节课
                {
                    "startTime":"8:25",
                    "endTime":"10:00",
                    "subject":subject[0].subjectName
                }
            ]
        },
        {   //周四
            "day":"Thursday",
            "course":[
                //第一节课
                {
                    "startTime":"8:30",
                    "endTime":"10:05",
                    "subject":subject[0].subjectName
                },
                //第二节课
                {
                    "startTime":"10:25",
                    "endTime":"12:00",
                    "subject":subject[0].subjectName
                },
                //第三节课
                {
                    "startTime":"01:50",
                    "endTime":"03:05",
                    "subject":subject[0].subjectName
                },
                //第四节课
                {
                    "startTime":"3:25",
                    "endTime":"5:00",
                    "subject":subject[0].subjectName
                },
                //第五节课
                {
                    "startTime":"6:30",
                    "endTime":"8:05",
                    "subject":subject[0].subjectName
                },
                //第六节课
                {
                    "startTime":"8:25",
                    "endTime":"10:00",
                    "subject":subject[0].subjectName
                }
            ]
        },
        {
            "day":"friday",
            "course":[
                //第一节课
                {
                    "startTime":"8:30",
                    "endTime":"10:05",
                    "subject":subject[0].subjectName
                },
                //第二节课
                {
                    "startTime":"10:25",
                    "endTime":"12:00",
                    "subject":subject[1].subjectName
                },
                //第三节课
                {
                    "startTime":"01:50",
                    "endTime":"03:05",
                    "subject":subject[0].subjectName
                },
                //第四节课
                {
                    "startTime":"3:25",
                    "endTime":"5:00",
                    "subject":subject[0].subjectName
                },
                //第五节课
                {
                    "startTime":"6:30",
                    "endTime":"8:05",
                    "subject":subject[0].subjectName
                },
                //第六节课
                {
                    "startTime":"8:25",
                    "endTime":"10:00",
                    "subject":subject[0].subjectName
                }
            ]
        },
        {
            //周六
            "day":"saturday",
            "course":[
                //第一节课
                {
                    "startTime":"8:30",
                    "endTime":"10:05",
                    "subject":subject[0].subjectName
                },
                //第二节课
                {
                    "startTime":"10:25",
                    "endTime":"12:00",
                    "subject":subject[0].subjectName
                },
                //第三节课
                {
                    "startTime":"01:50",
                    "endTime":"03:05",
                    "subject":subject[0].subjectName
                },
                //第四节课
                {
                    "startTime":"3:25",
                    "endTime":"5:00",
                    "subject":subject[0].subjectName
                },
                //第五节课
                {
                    "startTime":"6:30",
                    "endTime":"8:05",
                    "subject":subject[0].subjectName
                },
                //第六节课
                {
                    "startTime":"8:25",
                    "endTime":"10:00",
                    "subject":subject[0].subjectName
                }
            ]
        }
    ]
};