var time = {
    "teacherId":"001",
    "teacherName":"鲁力",
    "semesterId":"1",
    "semester":"2015第一学期",
    "teacherSex":"男",
    "week":[
        {
            //星期一
            "day":"monday",
            "course":[
                //第一节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第二节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第三节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第四节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第五节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第六节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第七节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第八节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第九节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第十节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第十一节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第十二节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                }
            ]
        },
        {   //星期二
            "day":"tuesday",
            "course":[
                //第一节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第二节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第三节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第四节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第五节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第六节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第七节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第八节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第九节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第十节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第十一节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第十二节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                }
            ]
        },
        {
            //星期三
            "day":"wednesday",
            "course":[
                //第一节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第二节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第三节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第四节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第五节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第六节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第七节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第八节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第九节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第十节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第十一节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第十二节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                }
            ]
        },
        {   //星期四
            "day":"Thursday",
            "course":[
                //第一节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第二节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第三节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第四节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第五节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第六节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第七节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第八节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第九节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第十节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第十一节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第十二节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                }
            ]
        },
        {
            //星期五
            "day":"friday",
            "course":[
                //第一节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第二节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第三节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第四节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第五节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第六节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第七节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第八节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第九节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第十节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第十一节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第十二节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                }
            ]
        },
        {   //星期六
            "day":"saturday",
            "course":[
                //第一节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第二节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第三节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第四节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第五节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第六节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第七节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第八节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第九节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第十节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第十一节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第十二节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                }
            ]
        },
        {
            //星期七
            "day":"sunday",
            "course":[
                //第一节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第二节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第三节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第四节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第五节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第六节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第七节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第八节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第九节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第十节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第十一节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                },
                //第十二节课
                {
                    "startTime":"8:30",
                    "endTime":"9:45",
                    "subject":"数据挖掘",
                    "class":"1201",
                    "address":"18-415",
                    "allStudent":"43"
                }
            ]
        }

    ]


};